# My Variables

### Get request (auth)
GET http://localhost:5000/api/workouts/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmRmYTA5ZDhkYzAyNWRlNDA4ODAxNTIiLCJpYXQiOjE2NjAwMzIxNjYsImV4cCI6MTY2MDI5MTM2Nn0.9CXfY4Z1GT2BpuPboQ8RBcjBW9reveWAOuBjd9vp26Y

### Get contact
GET http://localhost:5000/api/workouts/62bed0b22137510e9b5deff6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmRmYTA5ZDhkYzAyNWRlNDA4ODAxNTIiLCJpYXQiOjE2NTk1MTcxMzAsImV4cCI6MTY1OTc3NjMzMH0.BDHIYwlUTLtfMbOc7btsDZZi5lNSrecuXJDHKhBwZVk



### Register User
POST http://localhost:5000/api/workouts/
Content-Type: application/json

{
   "title": "workbench1",
   "reps": 23,
   "load":50
}

### Register User
PATCH  http://localhost:5000/api/workouts/62bed0b22137510e9b5deff6
Content-Type: application/json

{
   "title": "updated goal"
}


### loginuser
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
   "email": "abc@gmailsdww.com",
   "password": "ABCabc123!"
}


### signupuser
POST http://localhost:5000/api/user/signup
Content-Type: application/json

{
   "email": "abc@gmailsdww.com",
   "password": "ABCabc123!"
}


### Login User
POST http://localhost:5000/api/auth
Content-Type: application/json

{
   "email": "whatever@gmail.com",
   "password": "1234567"
}

### Delete
Delete http://localhost:5000/api/workouts/62bed0a52137510e9b5deff4